name: Setup Promtool
author: nhedger
description: Setup Promtool in GitHub Actions
branding:
  color: orange
  icon: terminal
inputs:
  token:
    description: GitHub Actions token to authenticate API requests
    required: true
    default: ${{ github.token }}
  version:
    description: The version of Prometheus for which to install Promtool
    required: true
    default: ""
runs:
  using: "node20"
  main: "dist/index.mjs"
